---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main template for base infrastructure stack supporting the Falcon Cloud Security Lab.  Creates an EKS cluster via eksctl and CodeBuild job, a Metasploit attacker instance, and other good stuff.'

Parameters:

  EnvAlias:
    Type: String
    Default: 'fcs-lab'
  psEnvHash:
    Type: AWS::SSM::Parameter::Value<String>
    Default: psEnvHash
    Description: 'Used when launching from startDeployInfra.sh or after creating setStackParameters.yaml stack'
  # AWS Account Dependencies
  psS3Bucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: psS3Bucket
    Description: 'Used when launching from startDeployInfra.sh or after creating setStackParameters.yaml stack'
  EnvHashInput:
    Type: String
    Default: ""
    Description: "Leave blank to use existing SSM Parameter 'psEnvHash'. Otherwise, a 5-character alphanumeric value is required."
  S3BucketInput:
    Type: String
    Default: ""
    Description: "Leave blank to use existing SSM Parameter 'psS3Bucket'. Otherwise, use your S3Bucket name that already contains FCSLab template files cloned from GitHub."
  S3Prefix:
    Type: String
    Default: 'deployInfra'

 # Shared K8S Attributes
  KubernetesVersion:
    Type: String
    AllowedValues: [ "1.25", "1.26", "1.27", "1.28", "1.29" ]
    Default: "1.28"
    Description: Kubernetes control plane version.
  EKSClusterName:
    Type: String
    Default: "fcs-lab"

 # Optional
  # RemoteAccessCIDR:
  #   Type: String
  #   Default: 1.1.1.1/32
  # PermissionsBoundary:
  #   Type: String
  #   Default: 'BoundaryForAdministratorAccess'
  # KeyPairName:
  #   Type: String
  #   Default: ''
  
Conditions:
  UseEnvHashInput: 
    !Not [!Equals [!Ref EnvHashInput, '']]
  UseS3BucketInput: 
    !Not [!Equals [!Ref S3BucketInput, '']]

Resources:

  InfraStackParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: set psInfraStack parameter for stack deletion cleanup
      Name: !If [UseEnvHashInput, !Sub 'psInfraStack-${EnvHashInput}', !Sub 'psInfraStack-${psEnvHash}']
      Type: String
      Value: !Ref "AWS::StackName"
      
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/iam.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/iam.yaml']
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
        S3Bucket: !If [UseS3BucketInput, !Ref S3BucketInput, !Ref psS3Bucket]
        # PermissionsBoundary: !Ref PermissionsBoundary

  VPCStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/vpc.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/vpc.yaml']
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
        S3Bucket: !If [UseS3BucketInput, !Ref S3BucketInput, !Ref psS3Bucket]
        EKSClusterName: !Ref EKSClusterName
        # PermissionsBoundary: !Ref PermissionsBoundary

  EKSCodeBuildStack:
      Type: AWS::CloudFormation::Stack
      DependsOn: IAMStack
      Properties:
        TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/eksCodeBuild.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/eksCodeBuild.yaml']
        Parameters:
          EnvAlias: !Ref EnvAlias
          EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
          EKSClusterName: !Ref EKSClusterName
          KubernetesVersion: !Ref KubernetesVersion
          VpcId: !GetAtt VPCStack.Outputs.VpcId 
          SubnetPrivate1: !GetAtt VPCStack.Outputs.SubnetPrivate1
          SubnetPrivate2: !GetAtt VPCStack.Outputs.SubnetPrivate2
          SubnetPublic1: !GetAtt VPCStack.Outputs.SubnetPublic1
          SubnetPublic2: !GetAtt VPCStack.Outputs.SubnetPublic2
          FCSRole: !GetAtt IAMStack.Outputs.FCSRole
          # PermissionsBoundary: !Ref PermissionsBoundary

  BastionStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EKSCodeBuildStack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/bastion.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/bastion.yaml']
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
        S3Bucket: !If [UseS3BucketInput, !Ref S3BucketInput, !Ref psS3Bucket]
        S3Prefix: !Ref S3Prefix
        VPCID: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.SubnetPublic1
        FCSInstanceProfile: !GetAtt IAMStack.Outputs.FCSInstanceProfile
        # KeyPairName: !Ref KeyPairName
        # RemoteAccessCIDR: !Ref RemoteAccessCIDR

  MetasploitStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/metasploit.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/metasploit.yaml']
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
        S3Bucket: !If [UseS3BucketInput, !Ref S3BucketInput, !Ref psS3Bucket]
        S3Prefix: !Ref S3Prefix
        VPCCIDR: !GetAtt VPCStack.Outputs.VpcCIDROut
        PublicSubnetCIDR: !GetAtt VPCStack.Outputs.PublicSubnet1CIDROut
        NATGatewayEIP: !GetAtt VPCStack.Outputs.NATGatewayEIP
        # KeyPairName: !Ref KeyPairName
        # RemoteAccessCIDR: !Ref RemoteAccessCIDR
        # PermissionsBoundary: !Ref PermissionsBoundary

  ConfidentialBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/vulBucket.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/vulBucket.yaml']
      Parameters:
        EnvAlias: !Ref EnvAlias
        EnvHash: !If [UseEnvHashInput, !Ref EnvHashInput, !Ref psEnvHash]
        S3Bucket: !If [UseS3BucketInput, !Ref S3BucketInput, !Ref psS3Bucket]
        S3Prefix: !Ref S3Prefix
        # PermissionsBoundary: !Ref PermissionsBoundary

  SSMConfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If [UseS3BucketInput, !Sub 'https://${S3BucketInput}.s3.amazonaws.com/${S3Prefix}/SSMConf.yaml', !Sub 'https://${psS3Bucket}.s3.amazonaws.com/${S3Prefix}/SSMConf.yaml']
 