AWSTemplateFormatVersion: '2010-09-09'
Description: 'Set stack parameters to join or recreate base stacks'

Parameters:
  EnvHash:
    Type: String
    Default: '' 
  S3Bucket:
    Type: String
    Default: ''
  SetEnvHashParameter:
    Type: String
    Default: 'true'
  SetS3BucketParameter:
    Type: String
    Default: 'true'

Conditions:
  SetEnvHash: 
    - !Equals
      - !Ref SetEnvHashParameter
      - 'true'

  SetS3Bucket:
    - !Equals
      - !Ref SetS3BucketParameter
      - 'true'

  SetInfraStackName:
    - !Equals
      - '{{resolve:ssm:FCSLab-InfraStack}}'
      - ''

  SetFalconStackName:
    - !Equals
      - '{{resolve:ssm:FCSLab-FalconStack}}'
      - ''
      
Resources:
  EnvHashParameter:
    Type: AWS::SSM::Parameter
    Condition: SetEnvHash 
    Properties:
      AllowedPattern: "^[a-zA-Z0-9]{5}$"
      Description: EnvHash parameter for related stacks
      Name: "FCSLab-EnvHash"
      Type: String
      Value: !Ref EnvHash

  S3BucketParameter:
    Type: AWS::SSM::Parameter
    Condition: SetS3Bucket
    Properties:
      Description: EnvHash parameter for related stacks
      Name: "FCSLab-EnvHash"
      Type: String
      Value: !Ref S3Bucket

  InfraStackParameter:
    Type: AWS::SSM::Parameter
    Condition: SetInfraStackName
    Properties:
      Description: Infra Stack name for Stack Deletion Lambda
      Name: "FCSLab-InfraStack"
      Type: String
      Value: !Sub 'fcs-infra-stack-${EnvHash}'

  FalconStackParameter:
    Type: AWS::SSM::Parameter
    Condition: SetFalconStackName
    Properties:
      Description: Falcon Stack name for Stack Deletion Lambda
      Name: "FCSLab-FalconStack"
      Type: String
      Value: !Sub 'fcs-falcon-stack-${EnvHash}'

Outputs:
  EnvHash:
    Value: !Ref EnvHash

  S3Bucket:
    Value: !Ref S3Bucket

