AWSTemplateFormatVersion: '2010-09-09'
Description: 'Set stack parameters to join or recreate base stacks'

Parameters:
  EnvHash:
    Description: '5-digit alphanueric string'
    AllowedPattern: "^[a-zA-Z0-9]{5}$"
    Type: String
    Default: '' 
  S3Bucket:
    Description: 'S3 bucketName where FCS-Lab templates are located in two prefixes: deployInfra and deployFalcon.'
    Type: String
    Default: ''
  InfraStackName:
    Description: 'Name of the FCS-Lab Infra stack to join.'
    Type: String
    Default: ''
  LoggingBucket:
    Description: 'S3 bucket for logging access associated with the "confidential bucket" created by the InfraStack deployment.'
    Type: String
    Default: ''

Resources:
  EnvHashParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Set adhoc EnvHash parameter -- 5-digit alphanueric string
      Name: "psEnvHash"
      Type: String
      AllowedPattern: "^[a-zA-Z0-9]{5}$"
      Value: !Ref EnvHash
  
  S3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Set S3Bucket name where FCS-Lab templates are located. (Typically from a previous git clone or workshop).
      Name: "psS3Bucket"
      Type: String
      Value: !Ref S3Bucket

  InfraStackParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Set name of the FCS-Lab Infra stack to join.
      Name: !Sub "psInfraStack-${EnvHash}"
      Type: String
      Value: !Ref InfraStackName
  
  LoggingBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Set S3 bucket for logging access associated with the "confidential bucket" created by InfraStack deployment.
      Name: !Sub "psLoggingBucket-${EnvHash}"
      Type: String
      Value: !Ref LoggingBucket
