AWSTemplateFormatVersion: '2010-09-09'
Description: Stores Parameters and Secrets for later use

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Falcon API Credentials
        Parameters:
          - FalconClientID
          - FalconClientSecret
          - FalconCID
          - CrowdStrikeCloud
      
    ParameterLabels:
      FalconClientID:
        default: Falcon API Client ID
      FalconClientSecret:
        default: Falcon API Secret
      FalconCID:
        default: Falcon Customer ID (CID)
      CrowdStrikeCloud:
        default: CrowdStrike Cloud

Parameters:
  FalconClientID:
    Description: Your Falcon OAuth2 Client ID.
    NoEcho: 'true'
    Type: String
  FalconClientSecret:
    Description: Your Falcon OAuth2 API Secret.
    NoEcho: 'true'
    Type: String
  FalconCID:
    Description: Falcon Customer ID
    NoEcho: 'true'
    Type: String
  CrowdStrikeCloud:
    Type: String
    Default: us-1
    AllowedValues: [ "us-1", "us-2", "eu-1" ]
    Description: The cloud region where your Falcon CID is hosted
    
Resources:
  CrowdStrikeSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'FalconAPIKey'
      Description: 'Client ID and Secret for the Falcon API'
      SecretString: !Sub |
        {
          "client_id": "${FalconClientID}",
          "client_secret": "${FalconClientSecret}",
          "cid": "${FalconCID}",
          "cs_cloud":"${CrowdStrikeCloud}"
        }