AWSTemplateFormatVersion: '2010-09-09'
Description: Stores Parameters and Secrets for later use

Parameters:
  FalconSecretName:
    Description: Name of the Secrets Manager secret 
    Type: String
    Default: "crowdstrike-falcon-api"
  FalconClientId:
    Description: Your Falcon OAuth2 Client ID.
    NoEcho: 'true'
    Type: String
    Default: ""
  FalconClientSecret:
    Description: Your Falcon OAuth2 API Secret.
    NoEcho: 'true'
    Type: String
    Default: ""
  FalconCID:
    Description: Falcon Customer ID
    NoEcho: 'true'
    Type: String
    Default: ""
  CrowdStrikeCloud:
    Type: String
    Default: ""
    #AllowedValues: [ "us-1", "us-2", "eu-1" ]
    Description: The cloud region where your Falcon CID is hosted (use either us-1, us-2, or eu-1)
    
Resources:
  FalconSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'crowdstrike-falcon-api'
      Description: 'Client ID and Secret for the Falcon API'
      SecretString: !Sub |
        {
          "FalconClientId":"${FalconClientId}", 
          "FalconSecret":"${FalconClientSecret}",
          "FalconCID":"${FalconCID}",
          "CSCloud":"${CrowdStrikeCloud}" 
        }

  # VariableTest:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     # BucketName: 
  #     #   !If 
  #     #     - UseInputSecret
  #     #     - !Sub 'input-${FalconClientID}'
  #     #     - !Sub "secret-{{resolve:secretsmanager:/crowdstrike-falcon-api:SecretString:FalconClientId}}"
  #     BucketName: !If [UseInputSecret, !Sub '$FalconClientID', "{{resolve:secretsmanager:/crowdstrike-falcon-api:SecretString:FalconClientId}}"]

Outputs:
  SecretARN:
    Description: Falcon Secret ARN
    Value: !Ref FalconSecrets
    Export:
      Name: FalconSecretArn